-- Slate (tittel-platform) schema — Supabase Postgres.
-- Idempotent: safe to run repeatedly (applied on every boot, see server/migrate.ts).
-- Shape is authoritative in PLAN.md §5 — keep this file and that section in sync.
--
-- Conventions: id = nanoid text PK generated by the app (packages/shared), not a
-- DB default. created_at timestamptz default now() everywhere. Every tenant-owned
-- table carries org_id with an index. Soft-delete via archived_at where noted.

-- =============================================================================
-- 5.1 Tenancy & identity
-- =============================================================================

create table if not exists orgs (
  id                     text primary key,
  name                   text not null,
  plan                   text not null default 'trial'
                         check (plan in ('trial','solo','studio','free')),
  trial_ends_at          timestamptz,
  stripe_customer_id     text,
  stripe_subscription_id text,
  settings               jsonb not null default '{}',
  created_at             timestamptz not null default now()
);

create table if not exists users (
  id            text primary key,
  org_id        text not null references orgs(id) on delete cascade,
  supabase_uid  text not null unique,
  email         text not null,
  display_name  text,
  role          text not null default 'owner' check (role in ('owner','tutor')),
  created_at    timestamptz not null default now()
);
create index if not exists users_org_idx on users(org_id);

create table if not exists students (
  id            text primary key,
  org_id        text not null references orgs(id) on delete cascade,
  name          text not null,
  email         text,
  portal_token  text not null unique,
  report_token  text unique,
  notes         text,
  archived_at   timestamptz,
  created_at    timestamptz not null default now()
);
create index if not exists students_org_idx on students(org_id);

create table if not exists groups (
  id          text primary key,
  org_id      text not null references orgs(id) on delete cascade,
  name        text not null,
  archived_at timestamptz,
  created_at  timestamptz not null default now()
);
create index if not exists groups_org_idx on groups(org_id);

create table if not exists group_members (
  group_id   text not null references groups(id) on delete cascade,
  student_id text not null references students(id) on delete cascade,
  primary key (group_id, student_id)
);

-- =============================================================================
-- 5.2 Content
-- =============================================================================

create table if not exists tags (
  id        text primary key,
  org_id    text not null references orgs(id) on delete cascade,
  name      text not null,
  parent_id text references tags(id) on delete set null
);
create index if not exists tags_org_idx on tags(org_id);

create table if not exists problems (
  id                 text primary key,
  org_id             text not null references orgs(id) on delete cascade,
  type               text not null check (type in ('mc','multi','numeric','text','frq')),
  stem_latex         text not null,
  choices            jsonb not null default '[]',
  correct            jsonb,
  accept             jsonb not null default '[]',
  explanation_latex  text,
  figures            jsonb not null default '[]',
  difficulty         int,
  source             text,
  archived_at        timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists problems_org_idx on problems(org_id);

create table if not exists problem_tags (
  problem_id text not null references problems(id) on delete cascade,
  tag_id     text not null references tags(id) on delete cascade,
  primary key (problem_id, tag_id)
);

create table if not exists problem_sets (
  id          text primary key,
  org_id      text not null references orgs(id) on delete cascade,
  title       text not null,
  description text,
  template    text not null default 'neutral' check (template in ('neutral','sat')),
  archived_at timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists problem_sets_org_idx on problem_sets(org_id);

create table if not exists set_problems (
  set_id     text not null references problem_sets(id) on delete cascade,
  problem_id text not null references problems(id) on delete cascade,
  ordinal    int not null,
  primary key (set_id, problem_id)
);
create index if not exists set_problems_set_idx on set_problems(set_id, ordinal);

create table if not exists lessons (
  id          text primary key,
  org_id      text not null references orgs(id) on delete cascade,
  title       text not null,
  doc         jsonb not null default '{}',
  version     int not null default 1,
  archived_at timestamptz,
  updated_at  timestamptz not null default now()
);
create index if not exists lessons_org_idx on lessons(org_id);

create table if not exists lesson_tags (
  lesson_id text not null references lessons(id) on delete cascade,
  tag_id    text not null references tags(id) on delete cascade,
  primary key (lesson_id, tag_id)
);

-- =============================================================================
-- 5.3 Assignments & attempts
-- =============================================================================

create table if not exists assignments (
  id             text primary key,
  org_id         text not null references orgs(id) on delete cascade,
  set_id         text not null references problem_sets(id),
  title          text,
  time_limit_sec int,                        -- null = untimed
  due_at         timestamptz,
  settings       jsonb not null default '{}',
  created_by     text references users(id),
  archived_at    timestamptz,
  created_at     timestamptz not null default now()
);
create index if not exists assignments_org_idx on assignments(org_id);

create table if not exists assignment_student (
  assignment_id text not null references assignments(id) on delete cascade,
  student_id    text not null references students(id) on delete cascade,
  primary key (assignment_id, student_id)
);

create table if not exists attempts (
  id             text primary key,
  org_id         text not null references orgs(id) on delete cascade,
  assignment_id  text not null references assignments(id) on delete cascade,
  student_id     text not null references students(id) on delete cascade,
  attempt_token  text not null unique,
  started_at     timestamptz,
  submitted_at   timestamptz,
  status         text not null default 'pending'
                 check (status in ('pending','active','submitted','expired')),
  unique (assignment_id, student_id)
);
create index if not exists attempts_org_idx on attempts(org_id);

create table if not exists responses (
  id                text primary key,
  attempt_id        text not null references attempts(id) on delete cascade,
  problem_id        text not null references problems(id),
  answer            jsonb,
  is_correct        boolean,
  marked_for_review boolean not null default false,
  time_spent_ms     int not null default 0,
  change_count      int not null default 0,
  updated_at        timestamptz not null default now(),
  unique (attempt_id, problem_id)
);

-- =============================================================================
-- 5.4 Live teaching
-- =============================================================================

create table if not exists classes (
  id          text primary key,
  org_id      text not null references orgs(id) on delete cascade,
  name        text not null,
  slug        text not null,
  mode        text not null default 'individual' check (mode in ('individual','large')),
  group_id    text references groups(id) on delete set null,
  archived_at timestamptz,
  unique (org_id, slug)
);
create index if not exists classes_org_idx on classes(org_id);

create table if not exists boards (
  id                  text primary key,
  org_id              text not null references orgs(id) on delete cascade,
  title               text,
  class_id            text references classes(id) on delete set null,
  student_id          text references students(id) on delete set null,
  snapshot            jsonb,
  snapshot_updated_at timestamptz,
  lesson_id           text references lessons(id) on delete set null,
  is_ephemeral        boolean not null default false,
  archived_at         timestamptz,
  created_at          timestamptz not null default now()
);
create index if not exists boards_org_idx on boards(org_id);

create table if not exists board_assets (
  id          text primary key,
  board_id    text not null references boards(id) on delete cascade,
  org_id      text not null references orgs(id) on delete cascade,
  storage_key text not null,
  mime        text not null,
  created_at  timestamptz not null default now()
);
create index if not exists board_assets_org_idx on board_assets(org_id);

create table if not exists sessions (
  id               text primary key,
  org_id           text not null references orgs(id) on delete cascade,
  board_id         text not null references boards(id) on delete cascade,
  started_at       timestamptz not null default now(),
  ended_at         timestamptz,
  participants     jsonb not null default '[]',
  quiz_results     jsonb,
  pdf_storage_key  text
);
create index if not exists sessions_org_idx on sessions(org_id);

create table if not exists quiz_events (
  id          text primary key,
  org_id      text not null references orgs(id) on delete cascade,
  session_id  text not null references sessions(id) on delete cascade,
  student_id  text references students(id) on delete set null,
  guest_name  text,
  qid         text not null,
  answer      jsonb,
  is_correct  boolean,
  elapsed_ms  int,
  created_at  timestamptz not null default now()
);
create index if not exists quiz_events_org_idx on quiz_events(org_id);
